// Copyright (c) 2025 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.article3.optics;

import org.higherkindedj.article3.ast.BinaryOp;
import org.higherkindedj.article3.ast.Expr;
import org.higherkindedj.article3.ast.Expr.Binary;

/**
 * Lenses for the Binary record.
 *
 * <p>These would be auto-generated by {@code @GenerateLenses} in production with higher-kinded-j.
 */
public final class BinaryLenses {
  private BinaryLenses() {}

  /** Lens focusing on the left operand of a Binary expression. */
  public static Lens<Binary, Expr> left() {
    return Lens.of(Binary::left, (l, b) -> new Binary(l, b.op(), b.right()));
  }

  /** Lens focusing on the operator of a Binary expression. */
  public static Lens<Binary, BinaryOp> op() {
    return Lens.of(Binary::op, (o, b) -> new Binary(b.left(), o, b.right()));
  }

  /** Lens focusing on the right operand of a Binary expression. */
  public static Lens<Binary, Expr> right() {
    return Lens.of(Binary::right, (r, b) -> new Binary(b.left(), b.op(), r));
  }
}
