// Copyright (c) 2025 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.article3.optics;

import org.higherkindedj.article3.ast.Expr;
import org.higherkindedj.article3.ast.Expr.Conditional;

/**
 * Lenses for the Conditional record.
 *
 * <p>These would be auto-generated by {@code @GenerateLenses} in production with higher-kinded-j.
 */
public final class ConditionalLenses {
  private ConditionalLenses() {}

  /** Lens focusing on the condition of a Conditional expression. */
  public static Lens<Conditional, Expr> cond() {
    return Lens.of(Conditional::cond, (c, cnd) -> new Conditional(c, cnd.then_(), cnd.else_()));
  }

  /** Lens focusing on the then branch of a Conditional expression. */
  public static Lens<Conditional, Expr> then_() {
    return Lens.of(Conditional::then_, (t, cnd) -> new Conditional(cnd.cond(), t, cnd.else_()));
  }

  /** Lens focusing on the else branch of a Conditional expression. */
  public static Lens<Conditional, Expr> else_() {
    return Lens.of(Conditional::else_, (e, cnd) -> new Conditional(cnd.cond(), cnd.then_(), e));
  }
}
