// Copyright (c) 2025 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.article3.optics;

import java.util.Optional;
import org.higherkindedj.article3.ast.Expr;
import org.higherkindedj.article3.ast.Expr.Binary;
import org.higherkindedj.article3.ast.Expr.Conditional;
import org.higherkindedj.article3.ast.Expr.Literal;
import org.higherkindedj.article3.ast.Expr.Variable;

/**
 * Prisms for the Expr sealed interface.
 *
 * <p>These would be auto-generated by {@code @GeneratePrisms} in production with higher-kinded-j.
 */
public final class ExprPrisms {
  private ExprPrisms() {}

  /** Prism focusing on Literal expressions. */
  public static Prism<Expr, Literal> literal() {
    return Prism.of(
        expr -> expr instanceof Literal l ? Optional.of(l) : Optional.empty(), lit -> lit);
  }

  /** Prism focusing on Variable expressions. */
  public static Prism<Expr, Variable> variable() {
    return Prism.of(
        expr -> expr instanceof Variable v ? Optional.of(v) : Optional.empty(), var -> var);
  }

  /** Prism focusing on Binary expressions. */
  public static Prism<Expr, Binary> binary() {
    return Prism.of(
        expr -> expr instanceof Binary b ? Optional.of(b) : Optional.empty(), bin -> bin);
  }

  /** Prism focusing on Conditional expressions. */
  public static Prism<Expr, Conditional> conditional() {
    return Prism.of(
        expr -> expr instanceof Conditional c ? Optional.of(c) : Optional.empty(), cond -> cond);
  }
}
