// Copyright (c) 2025 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.article3.optics;

import org.higherkindedj.article3.ast.Expr.Literal;

/**
 * Lenses for the Literal record.
 *
 * <p>These would be auto-generated by {@code @GenerateLenses} in production with higher-kinded-j.
 */
public final class LiteralLenses {
  private LiteralLenses() {}

  /** Lens focusing on the value field of a Literal. */
  public static Lens<Literal, Object> value() {
    return Lens.of(Literal::value, (v, _) -> new Literal(v));
  }
}
