// Copyright (c) 2025 Magnus Smith
// Licensed under the MIT License. See LICENSE.md in the project root for license information.
package org.higherkindedj.article3.optics;

import org.higherkindedj.article3.ast.Expr.Variable;

/**
 * Lenses for the Variable record.
 *
 * <p>These would be auto-generated by {@code @GenerateLenses} in production with higher-kinded-j.
 */
public final class VariableLenses {
  private VariableLenses() {}

  /** Lens focusing on the name field of a Variable. */
  public static Lens<Variable, String> name() {
    return Lens.of(Variable::name, (n, _) -> new Variable(n));
  }
}
